version: '3.7'

networks:
    NetworkApp:
        driver: bridge
        name: NetApp
        ipam:
            driver: default
            config:
                - subnet: 172.31.0.0/16
    NetTraefik:
        driver: overlay
        name: NetTraefik

volumes:
    mySQLData:
    mongoDBData:
    redisData:
    localBindApp:
        driver: local
        driver_opts:
            type: none
            device: $PWD/${LOCAL_SRC}
            o: bind

services:

    # traefik:
    #     image: traefik:1.7-alpine
    #     hostname: traefik
    #     container_name: traefik
    #     # command: |
    #     #     - "--configFile=/traefik.toml"
    #     labels:
    #         traefik.enable: "true"
    #         traefik.backend: "traefik"
    #         traefik.frontend.rule: "Host:traefik.example.com"
    #         traefik.port: "8099"
    #     expose:
    #         # Traefik dashboard port
    #         - 8099
    #     ports:
    #         - target: 80
    #           published: 80
    #           protocol: tcp
    #         - target: 443
    #           published: 443
    #           protocol: tcp
    #     volumes:
    #         - ./nginx/certs/:/certs/:ro
    #         - ./traefik/traefik.toml:/traefik.toml:ro
    #         - /var/run/docker.sock:/var/run/docker.sock:ro
    #     restart: on-failure
    #     networks:
    #         NetTraefik:

    # whoami:
    #     hostname: whoami
    #     container_name: whoami
    #     image: containous/whoami
    #     labels:
    #         traefik.enable: true
    #         traefik.frontend.rule: "Host:whoami.example.com"
    #     networks:
    #         NetTraefik:

    # # redis-cli -h 127.0.0.1 -p 63781 -a 'HQD3{9S-u(qnxK@'
    redis:
        image: redis:5-alpine
        hostname: redis
        container_name: redis
        ports:
            - "63781:6379"
        volumes:
            - ./redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
            - redisData:/data
        command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--appendonly", "yes"]
        restart: on-failure
        networks:
            NetworkApp:
                ipv4_address: 172.31.1.2
        healthcheck:
            test: ["CMD-SHELL", "redis-cli -h 127.0.0.1 -p 6379 -a HQD3{9S-u(qnxK@ --no-auth-warning PING"]
            interval: 30s
            timeout: 5s
            retries: 5

    # # mysql -h 127.0.0.1 -P 33061 -uapp -psecret \
    # #     --ssl-ca=mysql/ssl/ca.pem \
    # #     --ssl-cert=mysql/ssl/client-cert.pem \
    # #     --ssl-key=mysql/ssl/client-key.pem
    database:
        image: mysql:5.7
        hostname: database
        container_name: database
        command: ["mysqld"]
        volumes:
            - ./mysql/ssl/ca-key.pem:/etc/mysql-ssl/ca-key.pem:ro
            - ./mysql/ssl/ca.pem:/etc/mysql-ssl/ca.pem:ro
            - ./mysql/ssl/client-cert.pem:/etc/mysql-ssl/client-cert.pem:ro
            - ./mysql/ssl/client-key.pem:/etc/mysql-ssl/client-key.pem:ro
            - ./mysql/ssl/private_key.pem:/etc/mysql-ssl/private_key.pem:ro
            - ./mysql/ssl/public_key.pem:/etc/mysql-ssl/public_key.pem:ro
            - ./mysql/ssl/server-cert.pem:/etc/mysql-ssl/server-cert.pem:ro
            - ./mysql/ssl/server-key.pem:/etc/mysql-ssl/server-key.pem:ro
            - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro
            - mySQLData:/var/lib/mysql
        env_file:
            - ./mysql/mysql.env
        environment:
            MYSQL_DATABASE: app
            MYSQL_USER: app
        ports:
            - "29011:3306"
        restart: on-failure
        networks:
            NetworkApp:
                ipv4_address: 172.31.1.3
        healthcheck:
            test: "export MYSQL_PWD=root; mysqladmin -h '127.0.0.1' --user=root --silent ping"
            interval: 30s
            timeout: 10s
            retries: 3

    # # mongo --ssl \
    # #       --sslCAFile rootCA.pem --sslPEMKeyFile mongodb.pem \
    # #       --host 127.0.0.1 --port 29019 -u "root" -p "secret" --authenticationDatabase admin
    # # @see https://medium.com/@rajanmaharjan/secure-your-mongodb-connections-ssl-tls-92e2addb3c89
    mongodb:
        image: mongo:4.1
        hostname: mongodb
        container_name: mongodb
        command: ["mongod", "--bind_ip_all", "--config", "/etc/mongo/mongod.conf"]
        ports:
            - "29019:27017"
        volumes:
            - ./mongodb/mongod.conf:/etc/mongo/mongod.conf:ro
            - ./mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
            - ./mongodb/ssl/rootCA.pem:/etc/ssl/ca.pem:ro
            - ./mongodb/ssl/mongodb.pem:/etc/ssl/mongodb.pem:ro
            - mongoDBData:/data/db
        environment:
            # MONGO_INITDB_DATABASE: admin
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: secret
        restart: on-failure
        networks:
            NetworkApp:
                ipv4_address: 172.31.1.4

    webserver:
        image: ${WEBSERVER_IMAGE}
        hostname: webserver
        container_name: webserver
        build:
            context: ./nginx
            dockerfile: Dockerfile
        ports:
            - "${PORT_HTTP}:80"
            - "${PORT_HTTPS}:443"
        labels:
            - traefik.enable=true
            - traefik.frontend.rule=Host:www.example.com
        networks:
            NetworkApp:
                ipv4_address: 172.31.1.5
        environment:
            DOMAIN_APP: ${DOMAIN_APP}
            REMOTE_SRC: ${REMOTE_SRC}
        depends_on:
            - app
        restart: unless-stopped
        ulimits:
            nproc: 8192
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 32768
                hard: 65535
        working_dir: ${REMOTE_SRC}
        volumes:
            - type: volume
              source: localBindApp
              target: ${REMOTE_SRC}
        links:
            - "app:php-fpm"

    # # docker-compose exec app php artisan key:generate
    # # docker-compose exec app php artisan migrate --seed
    app:
        image: ${APP_IMAGE}
        hostname: app
        container_name: app
        build:
            context: ${LOCAL_SRC}
            dockerfile: ./docker/app/Dockerfile
            args:
                PROJECT_ENVIRONMENT: ${PROJECT_ENVIRONMENT}
        working_dir: ${REMOTE_SRC}
            # When you set the same environment variable in multiple files, here’s the priority used by Compose to choose which value to use:
            # 1. Compose file
            # 2. Shell environment variables
            # 3. Environment file
            # 4. Dockerfile
            # 5. Variable is not defined
        env_file:
            - ./app/app.env
        environment:
            DB_PASSWORD: root
            DOMAIN_APP: ${DOMAIN_APP}
            REMOTE_SRC: ${REMOTE_SRC}
        depends_on: ['redis', 'database']
        ulimits:
            nproc: 2048
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 32768
                hard: 65535
        volumes:
            # # Used [:delegated] or [:cached] mode here on docker for MAC for faster disk I/O
            - ${LOCAL_SRC}:${REMOTE_SRC}:delegated
            # - ./app/config/php.ini-production.ini:/usr/local/etc/php/php.ini:ro
            # - ./app/config/extensions/opcache.ini:/usr/local/etc/php/conf.d/docker-php-ext-opcache.ini
            # - ./app/config/extensions/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
        networks:
            NetworkApp:
                ipv4_address: 172.31.1.6
        tty: true
        stdin_open: true
        restart: unless-stopped
        dns:
            - 8.8.8.8
            - 8.8.4.4

    queue:
        image: app:queue
        hostname: queue
        container_name: queue
        working_dir: ${REMOTE_SRC}
        env_file:
            - ./app/app-queue.env
        environment:
            REMOTE_SRC: ${REMOTE_SRC}
        depends_on: ['redis', 'database', 'app']
        volumes:
            - ${LOCAL_SRC}:${REMOTE_SRC}:delegated
        networks:
            NetworkApp:
                ipv4_address: 172.31.1.7
        restart: on-failure

    scheduler:
        image: app:scheduler
        hostname: scheduler
        container_name: scheduler
        working_dir: ${REMOTE_SRC}
        env_file:
            - ./app/app-scheduler.env
        environment:
            REMOTE_SRC: ${REMOTE_SRC}
        depends_on: ['redis', 'database', 'app']
        volumes:
            - ${LOCAL_SRC}:${REMOTE_SRC}:delegated
        networks:
            NetworkApp:
                ipv4_address: 172.31.1.8
        restart: on-failure
