## Default Kibana configuration from kibana-docker
## from https://github.com/elastic/kibana-docker/blob/master/build/kibana/config/kibana.yml
## @see https://www.elastic.co/guide/en/kibana/current/settings.html

server.name: kibana
server.host: "0.0.0.0"
server.port: "5601"

elasticsearch.hosts: ["https://elasticsearch:9200"]
elasticsearch.username: kibana
# elasticsearch.password is stored in `kibana.keystore`
# elasticsearch.password: ${ELASTIC_PASSWORD}
elasticsearch.ssl.certificateAuthorities: ["/usr/share/kibana/config/certs/ca/ca.crt"]

server.ssl.enabled: false
# server.ssl.certificate: /usr/share/kibana/config/certs/kibana/kibana.crt
# server.ssl.key: /usr/share/kibana/config/certs/kibana/kibana.key

# xpack.monitoring.elasticsearch.hosts: ["https://elasticsearch:9200"]
# xpack.monitoring.elasticsearch.ssl.certificateAuthorities: "/usr/share/kibana/config/certs/ca/ca.crt"

xpack.monitoring.ui.enabled: true
xpack.monitoring.kibana.collection.enabled: true
xpack.monitoring.ui.container.elasticsearch.enabled: true
