---
version: '3.7'

services:

    setup_kibana:
        image: docker.elastic.co/kibana/kibana:${TAG_ELK}
        container_name: setup_kibana
        command: ['/bin/bash', '-c', 'cat /usr/local/bin/setup-kibana.sh | tr -d "\r" | bash']
        environment: ['ELASTIC_PASSWORD=${ELASTIC_PASSWORD}']
        working_dir: '/config'
        volumes:
            - './config:/config'
            - './scripts/setup-kibana.sh:/usr/local/bin/setup-kibana.sh:ro'
            - './config/ssl/ca/ca.crt:/usr/share/kibana/config/ca/ca.crt'
        depends_on: ['elasticsearch']
        networks:
            NetworkElastic:
                ipv4_address: 172.198.1.102
